### ISSUE TITLE
Is this file safe to use?

### ISSUE THREAD

**Issue by Gemsmith** [BoWang816/Software-recommend#1]
Thanks for this bit of code, BoWang.

Is this file safe for use? What is the source of this jar (XMindCrack.jar)?
I am new to coding & I don't know how to identify malware in code.

Please help with this.

**Comment by BoWang816** [comment]
I am glad that you asked such a question.
Yes, these files are safe. They are developed by some senior programmers in China. However, these related cracking softwares can only be used by individuals. It is strictly forbidden to be commercial. We cherish the labor results of developers and crack these softwares. It is used for simple daily use by individuals. If you need to use more related functions, please purchase genuine software as much as possible. 
Thank you very much.
